/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from './AccessControl';
import { AccessControlEnumerableContract } from './AccessControlEnumerable';
import { ERC1155Contract } from './ERC1155';
import { ERC1155BurnableContract } from './ERC1155Burnable';
import { ERC1155PausableContract } from './ERC1155Pausable';
import { ERC1155PresetMinterPauserContract } from './ERC1155PresetMinterPauser';
import { ERC165Contract } from './ERC165';
import { EscrowContract } from './Escrow';
import { IAccessControlContract } from './IAccessControl';
import { IAccessControlEnumerableContract } from './IAccessControlEnumerable';
import { IERC1155Contract } from './IERC1155';
import { IERC1155MetadataURIContract } from './IERC1155MetadataURI';
import { IERC1155ReceiverContract } from './IERC1155Receiver';
import { IERC165Contract } from './IERC165';
import { LiberMarketContract } from './LiberMarket';
import { LiberStickerContract } from './LiberSticker';
import { MigrationsContract } from './Migrations';
import { OwnableContract } from './Ownable';
import { PausableContract } from './Pausable';
import { PullPaymentContract } from './PullPayment';

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: 'AccessControl'): AccessControlContract;
      require(name: 'AccessControlEnumerable'): AccessControlEnumerableContract;
      require(name: 'ERC1155'): ERC1155Contract;
      require(name: 'ERC1155Burnable'): ERC1155BurnableContract;
      require(name: 'ERC1155Pausable'): ERC1155PausableContract;
      require(
        name: 'ERC1155PresetMinterPauser'
      ): ERC1155PresetMinterPauserContract;
      require(name: 'ERC165'): ERC165Contract;
      require(name: 'Escrow'): EscrowContract;
      require(name: 'IAccessControl'): IAccessControlContract;
      require(
        name: 'IAccessControlEnumerable'
      ): IAccessControlEnumerableContract;
      require(name: 'IERC1155'): IERC1155Contract;
      require(name: 'IERC1155MetadataURI'): IERC1155MetadataURIContract;
      require(name: 'IERC1155Receiver'): IERC1155ReceiverContract;
      require(name: 'IERC165'): IERC165Contract;
      require(name: 'LiberMarket'): LiberMarketContract;
      require(name: 'LiberSticker'): LiberStickerContract;
      require(name: 'Migrations'): MigrationsContract;
      require(name: 'Ownable'): OwnableContract;
      require(name: 'Pausable'): PausableContract;
      require(name: 'PullPayment'): PullPaymentContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from './AccessControl';
export {
  AccessControlEnumerableContract,
  AccessControlEnumerableInstance,
} from './AccessControlEnumerable';
export { ERC1155Contract, ERC1155Instance } from './ERC1155';
export {
  ERC1155BurnableContract,
  ERC1155BurnableInstance,
} from './ERC1155Burnable';
export {
  ERC1155PausableContract,
  ERC1155PausableInstance,
} from './ERC1155Pausable';
export {
  ERC1155PresetMinterPauserContract,
  ERC1155PresetMinterPauserInstance,
} from './ERC1155PresetMinterPauser';
export { ERC165Contract, ERC165Instance } from './ERC165';
export { EscrowContract, EscrowInstance } from './Escrow';
export {
  IAccessControlContract,
  IAccessControlInstance,
} from './IAccessControl';
export {
  IAccessControlEnumerableContract,
  IAccessControlEnumerableInstance,
} from './IAccessControlEnumerable';
export { IERC1155Contract, IERC1155Instance } from './IERC1155';
export {
  IERC1155MetadataURIContract,
  IERC1155MetadataURIInstance,
} from './IERC1155MetadataURI';
export {
  IERC1155ReceiverContract,
  IERC1155ReceiverInstance,
} from './IERC1155Receiver';
export { IERC165Contract, IERC165Instance } from './IERC165';
export { LiberMarketContract, LiberMarketInstance } from './LiberMarket';
export { LiberStickerContract, LiberStickerInstance } from './LiberSticker';
export { MigrationsContract, MigrationsInstance } from './Migrations';
export { OwnableContract, OwnableInstance } from './Ownable';
export { PausableContract, PausableInstance } from './Pausable';
export { PullPaymentContract, PullPaymentInstance } from './PullPayment';
