export const CM_PREFIX = 'CM::';

const WEBSOCKET_PREFIX = 'WEBSOCKET::';

export const WEBSOCKET_BEGIN_RECONNECT   = `${CM_PREFIX}${WEBSOCKET_PREFIX}BEGIN_RECONNECT`;
export const WEBSOCKET_RECONNECT_ATTEMPT = `${CM_PREFIX}${WEBSOCKET_PREFIX}RECONNECT_ATTEMPT`;
export const WEBSOCKET_RECONNECTED       = `${CM_PREFIX}${WEBSOCKET_PREFIX}RECONNECTED`;
export const WEBSOCKET_BROKEN            = `${CM_PREFIX}${WEBSOCKET_PREFIX}BROKEN`;
export const WEBSOCKET_CLOSED            = `${CM_PREFIX}${WEBSOCKET_PREFIX}CLOSED`;
export const WEBSOCKET_ERROR             = `${CM_PREFIX}${WEBSOCKET_PREFIX}ERROR`;
export const WEBSOCKET_MESSAGE           = `${CM_PREFIX}${WEBSOCKET_PREFIX}MESSAGE`;
export const WEBSOCKET_OPEN              = `${CM_PREFIX}${WEBSOCKET_PREFIX}OPEN`;

export const WEBSOCKET_CONNECT    = `${CM_PREFIX}${WEBSOCKET_PREFIX}CONNECT`;
export const WEBSOCKET_DISCONNECT = `${CM_PREFIX}${WEBSOCKET_PREFIX}DISCONNECT`;
export const WEBSOCKET_SEND       = `${CM_PREFIX}${WEBSOCKET_PREFIX}SEND`;

export const BROADCAST_MESSAGE = `${CM_PREFIX}BROADCAST_MESSAGE`;

export const RTC_CREATE_OFFER = `${CM_PREFIX}RTC_CREATE_OFFER`;