/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { EventData, PastEventOptions } from 'web3-eth-contract';

export interface PausableContract extends Truffle.Contract<PausableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<PausableInstance>;
}

export interface Paused {
  name: 'Paused';
  args: {
    account: string;
    0: string;
  };
}

export interface Unpaused {
  name: 'Unpaused';
  args: {
    account: string;
    0: string;
  };
}

type AllEvents = Paused | Unpaused;

export interface PausableInstance extends Truffle.ContractInstance {
  /**
   * Returns true if the contract is paused, and false otherwise.
   */
  paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  methods: {
    /**
     * Returns true if the contract is paused, and false otherwise.
     */
    paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
